### ISSUE TITLE
Setup link in wiki does not link to the setup page

### ISSUE THREAD

**Issue by mtorials** [montlikadani/RageMode#13]
When I click the link Setup in the Setup section I get redirected to the wiki home page and GitHub says "You don't hove the permission to update this page". I guess it is a link to the editor page instead of the rendered page.

**Comment by montlikadani** [comment]
You mean the Game Setup?

**Comment by mtorials** [comment]
Yes!

**Comment by montlikadani** [comment]
Well for me seems to be working. I logged out from my github account and still works.

**Comment by mtorials** [comment]
Maybe we are not talking about the same link.

Here is a picture:
![img1](https://user-images.githubusercontent.com/34133851/96373317-069c9f80-116c-11eb-854c-a36e1a7b2250.png)

There you can see the permission info banner in the top.

**Comment by montlikadani** [comment]
Fixed it, thanks.

**Comment by mtorials** [comment]
No problem!
