### ISSUE TITLE
Add Placeholders (Arena State, Arena players count)

### ISSUE THREAD

**Issue by FakeKoktis** [montlikadani/RageMode#14]
### Description

Please add Placeholders for plugin PlaceholderAPI, I want to have GUI Menus for all minigames, and I want to have here placeholders like %rm_{arena}_state% - Shows the state of game, %rm__{arena}_players% - Shows how many players are in Arena... That's all... Thank you.

**Comment by montlikadani** [comment]
Added, new placeholders: https://github.com/montlikadani/RageMode/wiki/PlaceholderAPI-placeholders
Plugin will be updated soon.
