### ISSUE TITLE
Sign not working

### ISSUE THREAD

**Issue by realSCYT** [montlikadani/RageMode#15]
I writed the sign like this
[ragemode]
[Augustin] -name of the arena

Plugin version: newest (31.01.2021)

Software: Spigot 1.16.4 

![image](https://user-images.githubusercontent.com/78316436/106392999-bd0f5200-63f4-11eb-9142-1f12c9e3f0ad.png)

**Comment by montlikadani** [comment]
The game name must be entered without parentheses.

**Comment by realSCYT** [comment]
I already tried that, didn't worked. 
![image](https://user-images.githubusercontent.com/78316436/106395217-52b0de80-6401-11eb-9c84-343cd5e2dfd2.png)

**Comment by montlikadani** [comment]
It seems that you not enabled signs in config.yml
https://github.com/montlikadani/RageMode/blob/6ca1e720ecb43e5aa16b37881ea46cb41c9a3094/src/main/resources/config.yml#L66-L67

**Comment by realSCYT** [comment]
Oh thank you, my bad
